name: Build Android APK (Akilli Kalkan)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo indir
      uses: actions/checkout@v4

    - name: Python kur
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Sistem paketleri
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk

    - name: Buildozer kur
      run: |
        pip install buildozer cython==0.29.36

    - name: Android ayarla
      run: buildozer android update

    - name: APK oluştur
      run: buildozer android debug

    - name: APK yükle
      uses: actions/upload-artifact@v4
      with:
        name: AkilliKalkan-APK
        path: bin/*.apk
